clusterName: opensearch
nodeGroup: master

singleNode: true
replicas: 1

persistence:
  enabled: true
  size: 20Gi
  storageClass: longhorn-retain

resources:
  requests:
    cpu: "100m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "3Gi"

opensearchJavaOpts: "-Xms512m -Xmx512m"

securityConfig:
  enabled: false

extraEnvs:
  - name: DISABLE_SECURITY_PLUGIN
    value: "true"

opensearchConfig:
  opensearch.yml: |
    cluster.name: opensearch
    network.host: 0.0.0.0
    plugins.security.disabled: true

    # Single-node lab setting
    discovery.type: single-node

    # Prevent replica issues in single-node mode
    cluster.routing.allocation.enable: all

    # Disk guardrails: stop before the PVC becomes completely full
    cluster.routing.allocation.disk.threshold_enabled: true
    cluster.routing.allocation.disk.watermark.low: "70%"
    cluster.routing.allocation.disk.watermark.high: "80%"
    cluster.routing.allocation.disk.watermark.flood_stage: "90%"
    cluster.info.update.interval: "1m"

startupProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 90

readinessProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 12


































# clusterName: opensearch
# nodeGroup: master

# singleNode: true
# replicas: 1

# persistence:
#   enabled: true
#   size: 20Gi
#   storageClass: longhorn-retain

# resources:
#   requests:
#     cpu: "100m"
#     memory: "1Gi"
#   limits:
#     cpu: "1"
#     memory: "2Gi"

# securityConfig:
#   enabled: false

# extraEnvs:
#   - name: DISABLE_SECURITY_PLUGIN
#     value: "true"
#   - name: OPENSEARCH_JAVA_OPTS
#     value: "-Xms512m -Xmx512m"

# opensearchConfig:
#   opensearch.yml: |
#     cluster.name: opensearch
#     network.host: 0.0.0.0
#     plugins.security.disabled: true

#     # Single-node lab setting
#     discovery.type: single-node

#     # Prevent replica issues in single-node mode
#     cluster.routing.allocation.enable: all

#     # Disk guardrails: stop before the PVC becomes completely full
#     cluster.routing.allocation.disk.threshold_enabled: true
#     cluster.routing.allocation.disk.watermark.low: "70%"
#     cluster.routing.allocation.disk.watermark.high: "80%"
#     cluster.routing.allocation.disk.watermark.flood_stage: "90%"
#     cluster.info.update.interval: "1m"

