apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    app.kubernetes.io/name: vault-backend
    app.kubernetes.io/part-of: platform-security
    app.kubernetes.io/component: external-vault
spec:
  provider:
    vault:
      server: "https://192.168.0.61:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: ConfigMap
        name: vault-ca-cert
        key: vault-ca.crt
        namespace: external-secrets
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "sre-decision-intelligence-eso"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
