apiVersion: v1
kind: Secret
metadata:
  name: vault-token-reviewer-token
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: vault-token-reviewer
  labels:
    app.kubernetes.io/name: vault-token-reviewer
    app.kubernetes.io/part-of: platform-security
    app.kubernetes.io/component: vault-kubernetes-auth
type: kubernetes.io/service-account-token
