apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sre-decision-api-secret
  namespace: sre-decision-intelligence
  labels:
    app.kubernetes.io/name: sre-decision-api-secret
    app.kubernetes.io/part-of: sre-decision-intelligence
    app.kubernetes.io/component: api-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sre-decision-api-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: sre-decision-intelligence/api
        property: DATABASE_URL
