apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sre-decision-postgres-secret
  namespace: sre-decision-intelligence
  labels:
    app.kubernetes.io/name: sre-decision-postgres-secret
    app.kubernetes.io/part-of: sre-decision-intelligence
    app.kubernetes.io/component: database-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sre-decision-postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: sre-decision-intelligence/postgres
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: sre-decision-intelligence/postgres
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: sre-decision-intelligence/postgres
        property: POSTGRES_PASSWORD
