apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bank-of-anthos-app.yaml
  - blackbox-exporter-app.yaml
  - bootstrap-namespaces-app.yaml
  - external-secrets-app.yaml
  - external-secrets-platform-config-app.yaml
  - fluent-bit-app.yaml
  - frontend-slo-resources-app.yaml
  - opensearch-app.yaml
  - opensearch-bootstrap-app.yaml
  - platform-cilium-lan-app.yaml
  - sre-decision-intelligence-external-secrets-app.yaml
