apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: observability

  sources:
    - repoURL: https://opensearch-project.github.io/helm-charts/
      chart: opensearch
      targetRevision: 2.27.0
      helm:
        valueFiles:
          - $values/platform/opensearch/values.yaml

    - repoURL: https://github.com/anselem-okeke/sre-decision-intelligence-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true





































#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: opensearch
#  namespace: argocd
#spec:
#  project: observability
#
#  source:
#    repoURL: https://opensearch-project.github.io/helm-charts/
#    chart: opensearch
#    targetRevision: 2.27.0
#    helm:
#      values: |
#        clusterName: opensearch
#        nodeGroup: master
#
#        singleNode: true
#        replicas: 1
#
#        persistence:
#          enabled: true
#          size: 20Gi
#          storageClass: longhorn-retain
#
#        resources:
#          requests:
#            cpu: "100m"
#            memory: "1Gi"
#          limits:
#            cpu: "1"
#            memory: "2Gi"
#
#        securityConfig:
#          enabled: false
#
#        extraEnvs:
#          - name: DISABLE_SECURITY_PLUGIN
#            value: "true"
#
#        opensearchConfig:
#          opensearch.yml: |
#            cluster.name: opensearch
#            network.host: 0.0.0.0
#            plugins.security.disabled: true
#
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: observability
#
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true