apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-cilium-lan
  namespace: argocd
spec:
  project: platform-networking

  source:
    repoURL: https://github.com/anselem-okeke/sre-decision-intelligence-gitops.git
    targetRevision: main
    path: platform/cilium-lan

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
