apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-decision-intelligence-external-secrets
  namespace: argocd
spec:
  project: platform-security

  source:
    repoURL: https://github.com/anselem-okeke/sre-decision-intelligence-gitops.git
    targetRevision: main
    path: platform/external-secrets/workloads/sre-decision-intelligence

  destination:
    server: https://kubernetes.default.svc
    namespace: sre-decision-intelligence

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
